name: Build Test

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    -
      name: Build and install web-greeter
      uses: "./.github/actions/build"
      with:
        distro: ubuntu
        web-greeter-build-dependencies: foo
